apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: my-app-redis
  description: My-App Redis Databse
  annotations:
    backstage.io/kubernetes-id: backend
  tags:
    - redis 
  links:
    - title: Documentation
      url: https://github.com/tomasferrarisenda/backstage-minikube-lab-reloaded
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
    - url: https://grafana.domain.com/
      title: metrics
      icon: analytics
      type: metrics-dashboard
    - url: https://grafana.domain.com/
      title: logs
      icon: assignment
      type: logs-dashboard  
spec:
  type: database
  lifecycle: production
  owner: my-app-redis-subteam
  system: my-app